### ISSUE TITLE
Option 1 Error

### ISSUE THREAD

**Issue by mgifford** [OpenAssessItToolkit/openassessit#20]
I went through Option 1.  Got down to run it and I got a strange linux error. 

$ pwd
/Users/mikegifford/openassessit
$ docker-compose run openassessit https://google.com thegoogles firefox
standard_init_linux.go:207: exec user process caused "no such file or directory"
$ docker-compose run openassessit https://google.com thegoogles chrome
standard_init_linux.go:207: exec user process caused "no such file or directory"

Seems to be related to this:
https://stackoverflow.com/questions/55106186/no-such-file-or-directory-with-docker-scratch-image

**Comment by joelhsmith** [comment]
Thanks Mike!  Since you are on the Docker version for this, can you run this info for me too?:

Operating system
docker --version

**Comment by mgifford** [comment]
You bet: Docker version 18.09.2, build 6247962

**Comment by joelhsmith** [comment]
When you open the entrypoint.sh file In your IDE, are the line endings set for LF or CRLF?  

bash might be just interpreting the line endings wrong, making it indicate an error. Could you try changing them locally and see if that fixes the issue?  If that fixes the issue, I'll change the line endings and commit.

**Comment by mgifford** [comment]
So this should do it:
  dos2unix entrypoint.sh 

But I'm getting the same error.

**Comment by joelhsmith** [comment]
Thanks for trying that.  Can you try the following:

Stay in your `/Users/mikegifford/openassessit` dir. That is correct.

I removed the `\` at the line endings in the following code block to simplify the file, just in case it is choking on those for some reason.  Can you replace the contents of the entrypoint.sh file with:

```bash
#!/bin/bash

mkdir -p /tmp/$2/assets;
cd openassessit;
lighthouse $1 --only-categories=accessibility --no-enable-error-reporting --disable-device-emulation --chrome-flags="--headless --window-size=1300,600 --no-sandbox --disable-gpu" --output="json" --output-path="/tmp/$2/$2.json";
python3 -m openassessit.markdown --input-file="/tmp/$2/$2.json" --output-file="/tmp/$2/$2.md" --user-template-path="/app/openassessit_templates/templates/";
python3 -m openassessit.to_html --input-file="/tmp/$2/$2.md" --output-file="/tmp/$2/$2.html" --user-template-path="/app/openassessit_templates/templates/";
python3 -m openassessit.capture --input-file="/tmp/$2/$2.json" --assets-dir="/tmp/$2/assets/" --sleep=4 --driver=$3;
zip -r /tmp/$2.zip /tmp/$2;
```

Remove the current image and instances:
```bash
docker-compose down --rmi all
```
Rebuild so it uses the new entrypoint.sh
```bash
docker-compose build
```
Rerun:
```bash
docker-compose run openassessit https://cats.com catshomefoo chrome
```

If it does generate a zip file it will have logs in it. A gist of those logs will help.

Thanks again Mike for helping me work through this. Since I can't replicate it, its hard to debug. 
 People might not give a project a second chance if it does not spin up right away. So working through these issues will really help.

**Comment by mgifford** [comment]
It's working for me now, thanks!

I'm not sure but it is possible that selenium wasn't installed.  I went to 
  https://pypi.org/project/selenium/#drivers

And I could still run `pip install -U selenium` so not sure if this led to a failing for option 2.

I probably should have also killed my instance with `docker-compose down --rmi all` before.
