### ISSUE TITLE
Prevent cleaning local storage

### ISSUE THREAD

**Issue by phongtran227** [OpenAssessItToolkit/openassessit#22]
How can I  keep the local storage for the needed process in the application? Just try to find out parameter that can use at [this](https://peter.sh/experiments/chromium-command-line-switches/#allarticles) page but there is no setting for that.

**Comment by joelhsmith** [comment]
Thanks for the question @phongtran227 . According to the Chromium documentation it looks like LocalStorage is enabled by default, since the only option available is to `--disable-local-storage`.  

Is this the Docker configuration or the native local install?  Are you getting an error message in the console or a message in the .log files?

**Comment by phongtran227** [comment]
Thanks for the quick reply @joelhsmith. I got the same issue on both Docker and Chrome Lighthouse. Seem we need to configure something with chromium. Beside I ran with Lighthouse in Chrome DevTools and it work fine.

**Comment by joelhsmith** [comment]
Since it works in devtools audit:

1. Run the Audit in Chrome Dev Tools.  
2. Download the JSON there.
2. Then run capture, markdown on that JSON file.

It might take a while to debug the real reason its clearing out local storage, but this solution gets you started.

**Comment by joelhsmith** [comment]
@phongtran227 Each time it runs it is opening up a new instance and session on the webbrowser.  Do you think the root cause is clearing local storage? or is the root cause that it is a new session so it is empty by default?

As I mentioned before this issue can be bypassed by running Lighthouse locally, downloading the JSON and running OpenAssessIt on that.

**Comment by phongtran227** [comment]
@joelhsmith Thank for your suggestion. Currently, I need to download the JSON from Audit then run OpenAssessIt.

**Comment by joelhsmith** [comment]
Cool. I'm going to close out the issue. Since it is running in headless chrome and always making a fresh instance, this is not something that the project can accommodate.  I am glad the work around is functioning well.
